name: chat_app
description: A minimal Flutter chat app that connects to a backend (WebSocket + REST).
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  web_socket_channel: ^2.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
